### ISSUE TITLE
Find all nearby canteens, favorite or not

### ISSUE THREAD

**Issue by cyroxx** [domoritz/open-mensa-android#14]
I have the impression that the current use case of the app can be stated as: You have a certain set of so-called "favorite canteens" which you like and you choose between them according to their meals on a daily basis. So each day, you go to the canteen that offers the meal of your choice.

However, this doesn't help you to discover canteens in a yet unknown location. Imagine a student that has recently arrived and now wants to explore her surroundings for opportunities to fill her stomach. A different example is a student that studies in Potsdam, but has to visit once or twice a university library in Berlin for her research and is interested in nearby canteens where she can have good food at an affordable (student) price.

While this may seem as a duplicate of #13 at first glance, I would like to point out that the approach is somewhat different. While #13 aims at a location-based selection of favorite canteens, I propose to use the user's current location as one main entry point in order to navigate through the information openmensa.org provides, without being bound to the concept of maintaining one's favorite canteens.

Having said that, the concept of favorite canteens is still valid and very useful, e.g. you could have a widget that gives you a short overview of your (closest) favorite canteens at lunch time.

The question remains how those two usage patterns (well-known environment vs. unknown environment) ought to be combined.
- Do you use two distinct Launchers for the different aspects (like Facebook/Facebook Messenger, Öffi Verbindungen/Öffi Haltestellen)?
- Or: Do you switch explicitly between those two inside the app explicitly (e.g. button click)?
- In the unknown environment setting, how do you turn a canteen into a favorite after having been there?

**Comment by l-jonas** [comment]
Closed by https://github.com/domoritz/open-mensa-android/commit/33e5286cfd0757d35b83212a92ba3fd4f252facb
