### ISSUE TITLE
By some reason app is not available in playstore for LG Nexus 5 device

### ISSUE THREAD

**Issue by olegflo** [domoritz/open-mensa-android#28]
By some reason app is not available in playstore for LG Nexus 5 device. 

http://i.gyazo.com/e5990d0eae5c4c77b5129481d8dd312d.png

I had a quick look into manifest, but haven't found any reason for this.

**Comment by scento** [comment]
This issue should be closed due to commit 3f66198a4e34ff03109b6b48ce1fc73d62758b08.
