### ISSUE TITLE
add quick search filter to mensa multiselect dialog

### ISSUE THREAD

**Issue by krichter722** [domoritz/open-mensa-android#29]
in order to be able to deal with different naming styles (start with city, "Mensa", or university name)

**Comment by domoritz** [comment]
That would be great. I don't have time to implement but take PRs

**Comment by sedrubal** [comment]
:+1:

**Comment by l-jonas** [comment]
Fixed by https://github.com/domoritz/open-mensa-android/commit/4b91a256581d52cb1994b74d83c575baca962d05
