### ISSUE TITLE
Mensa wählen

### ISSUE THREAD

**Issue by mondstern** [domoritz/open-mensa-android#42]
Ich wähle die stadt aus und dann passiert nichts weiter. 
Neuste version installiert 1.0.0.

**Comment by domoritz** [comment]
@l-jonas any idea what's going wrong here?

@mondstern can you try clearing the cache for the app (in android settings)?

**Comment by l-jonas** [comment]
After selecting a city, one has to enable location access and have got a location signal or use the show all button. In case this is not enough: Which city?

**Comment by mondstern** [comment]
@domoritz thanks. Its all okay now
