### ISSUE TITLE
Make headlines more obvious

### ISSUE THREAD

**Issue by Sogolumbo** [domoritz/open-mensa-android#43]
The headlines can't be distinguished from normal items in the menu.
I'd suggest giving the headlines a bold font.
Typical headlines distinguish different parts of a mensa which may be at different buildings and sell different food at different times. Hence it's relevamt to be able to visually distinguish the different areas.

I don't know if the APIs used here are able to provide the necessary info on wether a paragraph is a headline or not.

**Comment by l-jonas** [comment]
Are you thinking of making it like this?

![device-2020-07-20-144010](https://user-images.githubusercontent.com/43265000/87938494-30b7c600-ca86-11ea-80b7-b663bd0f7ca8.png)

**Comment by Sogolumbo** [comment]
Yeah, exactly.

**Comment by Sogolumbo** [comment]
But maybe leave the font size small or somewhere in between. It might take up too much space.

**Comment by l-jonas** [comment]
Is this better (it is bold now, with the old font size)? I don't want to use a custom font size/ I prefer to use one of the system font sizes (small, medium, large).

![device-2020-07-22-082617](https://user-images.githubusercontent.com/43265000/88142044-17815780-cbf5-11ea-9850-a1e47c602e03.png)

**Comment by Sogolumbo** [comment]
Yes, that's perfect. Thank you.
